### ISSUE TITLE
extended metatags and context sensitivity?

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/metatag_manager#1]
enhancing this plugin to be context sensitive would be a great addition.. 
so that keywords and descriptions would vary per page.
another related enhancement would be to add fb and twitter tags so that these apps pick up relevant images and data when pages are shared from elgg into them.

**Comment by jdalsem** [comment]
Core is thinking about an ability to be able to do this:
https://github.com/Elgg/Elgg/issues/693
https://github.com/Elgg/Elgg/issues/3315

a facebook related plugin can be found here: https://github.com/mapkyca/elgg-opengraph

This plugin will not get the requested feature any time soon.

**Comment by propertunist** [comment]
ah ok thanks, i'll look at that other plugin then
